"""GitHub Action entry point for AgentProbe."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import structlog

from src.graph.state import AgentProbeState
from src.graph.workflow import run_agentprobe
from src.integrations.github_app import GitHubClient

logger = structlog.get_logger(__name__)


def main() -> int:
    """Run AgentProbe as a GitHub Action."""
    github_token = os.environ.get("GITHUB_TOKEN", "")
    if not github_token:
        logger.error("GITHUB_TOKEN environment variable not set")
        return 1

    event_path = os.environ.get("GITHUB_EVENT_PATH", "")
    if not event_path or not Path(event_path).exists():
        logger.error("GITHUB_EVENT_PATH not set or file missing")
        return 1

    repo_full_name = os.environ.get("GITHUB_REPOSITORY", "")
    if not repo_full_name:
        logger.error("GITHUB_REPOSITORY not set")
        return 1

    # Parse event payload
    with open(event_path) as f:
        event = json.load(f)

    pr_number = event.get("pull_request", {}).get("number")
    if not pr_number:
        logger.error("No pull_request.number in event payload")
        return 1

    # Cold-start: generate style profile if missing
    style_path = Path(os.environ.get("STYLE_PROFILE_PATH", ".agentprobe/style-profile.yaml"))
    if not style_path.exists():
        logger.info("No style profile found — cold start mode")
        # Create a minimal default profile
        style_path.parent.mkdir(parents=True, exist_ok=True)
        style_path.write_text(
            "# Auto-generated by AgentProbe. Review and customize.\n"
            "naming:\n"
            "  functions: snake_case\n"
            "  classes: PascalCase\n"
            "  files: snake_case\n"
            "imports:\n"
            "  order: [builtin, external, internal, relative]\n"
            "forbidden: []\n"
        )
        logger.info("Generated default style profile at %s — please review", style_path)

    try:
        client = GitHubClient(github_token)
        pr_diff = client.get_pr_diff(repo_full_name, pr_number)
        head_sha = client.get_pr_head_sha(repo_full_name, pr_number)
    except Exception:
        logger.exception("Failed to fetch PR data from GitHub")
        return 1

    state = AgentProbeState(
        pr_diff=pr_diff,
        repo_path=".",
        pr_number=pr_number,
        repo_full_name=repo_full_name,
        architecture_report=None,
        pattern_report=None,
        regression_report=None,
        short_circuit=False,
        verdict=None,
        cached_functions=[],
        cost_tracker={},
    )

    try:
        result = run_agentprobe(state)
    except Exception:
        logger.exception("Pipeline execution failed")
        return 1

    verdict = result.get("verdict", {})
    comment = verdict.get("comment", "AgentProbe analysis complete.")

    try:
        client.post_pr_comment(repo_full_name, pr_number, comment)
        client.set_check_status(
            repo_full_name,
            head_sha,
            verdict.get("status", "PASS"),
            f"AgentProbe: {verdict.get('status', 'PASS')} (score: {verdict.get('score', 0):.0f})",
        )
    except Exception:
        logger.exception("Failed to post results to GitHub")
        return 1

    logger.info(
        "action_complete",
        verdict=verdict.get("status"),
        score=verdict.get("score"),
    )

    # Exit with code 1 if BLOCK to fail the check
    if verdict.get("status") == "BLOCK":
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
